<a href="https://colab.research.google.com/github/Nikhil5566/Machine-Learning/blob/main/Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [4]:
df = pd.read_csv('ML_data.csv')

In [5]:
df.head(11)

Country   Age   Salary Purchaged
0   France  44.0  72000.0        no
1    Spain  27.0  48000.0       yes
2  Germany  30.0  54000.0        no
3    Spain  38.0  61000.0        no
4  Germany  40.0      NaN       yes
5   France  35.0  58000.0       yes
6    Spain   NaN  52000.0        no
7   France  48.0  79303.0       yes
8  Germany  50.0  83000.0        no
9   France  37.0  87000.0       yes

In [6]:
duplicate = df.duplicated().sum()
duplicate

np.int64(0)

In [7]:
missing_values = df.isnull().sum()
missing_values

Country      0
Age          1
Salary       1
Purchaged    0
dtype: int64

In [8]:
df['Age'] = df['Age'].fillna(30)

In [9]:
df['Salary'] = df['Salary'].fillna(41000)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        10 non-null     float64
 2   Salary     10 non-null     float64
 3   Purchaged  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes


In [11]:
df.describe()

Age        Salary
count  10.000000     10.000000
mean   37.900000  63530.300000
std     7.766738  15846.400321
min    27.000000  41000.000000
25%    31.250000  52500.000000
50%    37.500000  59500.000000
75%    43.000000  77477.250000
max    50.000000  87000.000000

# ML

In [12]:
df = pd.read_csv('ML_data.csv')
X = df.iloc[:, :-1].values
Y = df.iloc[:, -1].values

In [13]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79303.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 87000.0]]


In [14]:
print(Y)

['no' 'yes' 'no' 'no' 'yes' 'yes' 'no' 'yes' 'no' 'yes']


### Taking care of missing values: [ with ML ]

In [15]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [16]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 66033.66666666667]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79303.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 87000.0]]


Encoding Categorical data

In [19]:
# Encoding the independent variable:

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [18]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 66033.66666666667]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79303.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 87000.0]]


In [21]:
# Encoding the Dependency variable;

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit_transform(Y)
y = le.fit_transform(Y)


In [23]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


Spliting the dataset into the training set and Test set.

In [37]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [34]:
print(X_train)

[[1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 40.0 66033.66666666667]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79303.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]


In [35]:
print(X_test)

[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 87000.0]]


In [38]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [43]:
print(y_test)

[0 1]


Feature Scaling

In [41]:
# Standardisation (google the formula)
# Normalisation (google the formula)

In [49]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:]) # [:, 3:] => Taking column Age and Salary
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [50]:
print(X_train)

[[1.0 0.0 0.0 1.2909944487358056 -0.19159184384578554 -1.1007776560031066]
 [1.0 0.0 1.0 -0.7745966692414833 -0.014117293757057846
  0.09515383253950309]
 [0.0 1.0 0.0 -0.7745966692414833 0.5667085065333239 0.6035972831326991]
 [1.0 0.0 0.0 1.2909944487358056 -0.3045301939022487 -0.333808933391994]
 [1.0 0.0 0.0 1.2909944487358056 -1.901801144700799 -1.4416526438302677]
 [0.0 1.0 0.0 -0.7745966692414833 1.1475343068237056 1.2259497921581386]
 [1.0 0.0 1.0 -0.7745966692414833 1.4379472069688966 1.5410034996573925]
 [0.0 1.0 0.0 -0.7745966692414833 -0.7401495441200352 -0.5894651742623649]]


In [52]:
print(X_test)

[[1.0 0.0 1.0 2.7755575615628907e-17 30.0 54000.0]
 [0.0 1.0 0.0 2.7755575615628907e-17 37.0 87000.0]]
